backend:
    name: github
    repo: PireJoseph/wwom
    branch: main
media_folder: static/assets
public_folder: /assets

collections:
  - name: service
    label: Services
    folder: src/content/services
    create: true
    fields:
      - { name: title, label: Titre, widget: string }
      - { name: order, label: Ordre, widget: number }
      - { label: picture, name: Image, widget: image }
      - { name: text, label: Texte, widget: text }
      - { name: body, label: Contenu, widget: markdown }
  - name: press
    label: Presse
    folder: src/content/press
    create: true
    fields:
      - { name: url, label: Url, widget: string }
      - { name: title, label: Titre, widget: string }
      - { label: logo, name: logo, widget: image }
      - { name: body, label: Contenu, widget: markdown }

files:
  - name: "site"
    label: "site"
    file: "src/content/site.md"
    fields: 
    - { label: logo, name: logo, widget: image }
    - { name: title, label: Titre, widget: string }

  - name: "hero"
    label: "Hero"
    file: "src/content/hero.md"
    fields:
      - { name: title, label: Titre, widget: string }
      - { name: action, label: Accroche, widget: text }
      - { name: body, label: Contenu, widget: markdown }

  - name: "presentation"
    label: "Présentation"
    file: "src/content/presentation.md"
    fields:
      - { name: title, label: Titre, widget: string }
      - { name: body, label: Contenu, widget: markdown }

  - name: "service"
    label: "Services"
    file: "src/content/services.md"
    fields:
      - { name: title, label: Titre, widget: string }
      - { name: body, label: Contenu, widget: markdown }

  - name: "testimonial"
    label: "Témoignage"
    file: "src/content/testimonial.md"
    fields:
      - { name: title, label: Titre, widget: string }
      - { name: body, label: Contenu, widget: markdown }

  - name: "footer"
    label: "Pied de page"
    file: "src/content/footer.md"
    fields:
      - { name: title, label: Titre, widget: string }
      - { name: body, label: Contenu, widget: markdown }

