backend:
    name: github
    repo: PireJoseph/wwom
    branch: main
media_folder: static/assets
public_folder: /assets

collections:
  - name: services
    label: Services
    folder: src/content/services
    create: true
    fields:
      - { name: title, label: Titre, widget: string }
      - { name: order, label: Ordre, widget: number }
      - { label: picture, name: Image, widget: image }
      - { name: text, label: Texte, widget: text }
      - { name: body, label: Contenu, widget: markdown }
    
  - name: press
    label: Presse
    folder: src/content/press
    create: true
    fields:
      - { name: title, label: Titre, widget: string }
      - { name: order, label: Ordre, widget: number }
      - { name: url, label: Url, widget: string }
      - { label: icon, name: Icone, widget: image }


  - name: pros
    label: Pros
    folder: src/content/pros
    create: true
    fields:
      - { name: title, label: Titre, widget: string }
      - { name: order, label: Ordre, widget: number }
      - { label: icon, name: Icône, widget: image }
      - { name: body, label: Contenu, widget: markdown }

  - name: site
    label: Site
    files: 
      - name: config
        label: Configuration
        file: src/content/items/site.md
        fields: 
        - { label: logo, name: Logo, widget: image }
        - { name: title, label: Titre, widget: string }

  - name: hero
    label: Hero
    files: 
    - name: content
      label: Contenu
      file: "src/content/items/hero.md"
      fields:
        - { name: title, label: Titre, widget: string }
        - { name: action, label: Accroche, widget: text }

  - name: presentation
    label: Présentation
    files: 
    - name: content
      label: Contenu
      file: "src/content/items/presentation.md"
      fields:
        - { name: title, label: Titre, widget: string }
        - { name: body, label: Contenu, widget: markdown }

  - name: action
    label: Appel à l'action
    files: 
    - name: content
      label: Contenu
      file: "src/content/items/action.md"
      fields:
        - { name: title, label: Titre, widget: string }
        - { name: body, label: Contenu, widget: markdown }

  - name: testimonial
    label: Témoignage
    files: 
    - name: content
      label: Contenu
      file: src/content/items/testimonial.md
      fields:
        - { name: title, label: Titre, widget: string }
        - { name: body, label: Contenu, widget: markdown }

  - name: footer
    label: Pied de Page
    files: 
    - name: content
      label: Contenu
      file: src/content/items/footer.md
      fields:
        - { name: title, label: Titre, widget: string }
        - { name: body, label: Contenu, widget: markdown }

