backend:
    name: git-gateway
    repo: PireJoseph/wwom
    branch: main
media_folder: static/assets
public_folder: /assets

collections:
  - name: site
    label: Site
    media_folder: ''
    public_folder: ''
    publish: false
    files: 
      - name: config
        label: Configuration
        file: src/content/site/site.md
        fields: 
        - { name: action, label: Accroche, widget: text }
        - { name: title, label: Titre, widget: string }
        - { name: logo, label: Logo, widget: image}
        
  - name: siteFooter
    label: Site - Pied de Page
    media_folder: ''
    public_folder: ''
    publish: false
    files: 
    - name: content
      label: Contenu
      file: src/content/site/footer.md
      fields:
        - { name: title, label: Titre, widget: string }
        - { name: body, label: Contenu, widget: markdown }       

  - name: indexServices
    label: Index - Services
    folder: src/content/pages/index/services
    media_folder: ''
    public_folder: ''
    create: true
    publish: false
    fields:
      - { name: title, label: Titre, widget: string }
      - { name: order, label: Ordre, widget: number }
      - { name: picture, label: Image, widget: image }
      - { name: text, label: Texte, widget: text }
      - { name: body, label: Contenu, widget: markdown }
    
  - name: indexPress
    label: Index - Presse
    folder: src/content/pages/index/press
    media_folder: ''
    public_folder: ''
    create: true
    publish: false
    fields:
      - { name: title, label: Titre, widget: string }
      - { name: heading, label: En-tête, widget: string }
      - { name: order, label: Ordre, widget: number }
      - { name: url, label: Url, widget: string }
      - { name: logo, label: Logo, widget: image }

  - name: indexPros
    label: Index - Pros
    folder: src/content/pages/index/pros
    media_folder: ''
    public_folder: ''
    create: true
    publish: false
    fields:
      - { name: title, label: Titre, widget: string }
      - { name: order, label: Ordre, widget: number }
      - { name: icon, label: Icône,  widget: image }
      - { name: body, label: Contenu, widget: markdown }

  - name: indexHero
    label: Index - Hero
    media_folder: ''
    public_folder: ''
    publish: false
    files: 
    - name: content
      label: Contenu
      file: "src/content/pages/index/hero/indexHero.md"
      fields:
        - { name: title, label: Titre, widget: string }
        - { name: action, label: Accroche, widget: text }
        - { name: image, label: Image, widget: image }

  - name: indexPresentation
    label: Index - Présentation
    media_folder: ''
    public_folder: ''
    publish: false
    files: 
    - name: content
      label: Contenu
      file: "src/content/pages/index/root/presentation.md"
      fields:
        - { name: title, label: Titre, widget: string }
        - { name: body, label: Contenu, widget: markdown }

  - name: indexTestimonial
    label: Index - Témoignage
    media_folder: ''
    public_folder: ''
    publish: false
    files: 
    - name: content
      label: Contenu
      file: src/content/pages/index/root/testimonial.md
      fields:
        - { name: title, label: Titre, widget: string }
        - { name: body, label: Contenu, widget: markdown }       

  - name: indexAction
    label: Index - Appel à l'action
    media_folder: ''
    public_folder: ''
    publish: false
    files: 
    - name: content
      label: Contenu
      file: "src/content/pages/index/root/action.md"
      fields:
        - { name: title, label: Titre, widget: string }
        - { name: body, label: Contenu, widget: markdown }


  - name: discoverHero
    label: Découvrir - Hero
    media_folder: ''
    public_folder: ''
    publish: false
    files: 
    - name: content
      label: Contenu
      file: src/content/pages/discover/hero/discoverHero.md
      fields:
        - { name: title, label: Titre, widget: string }
        - { name: image, label: Image, widget: image }